services:
  postgres:
    image: postgres:16-alpine
    container_name: backend-woow-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: woow
      POSTGRES_PASSWORD: woow_secret
      POSTGRES_DB: woow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U woow -d woow_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
